### PR TITLE
Added support for Python 3.13

### PR DESCRIPTION
**Pull request by alcides**

### CODE REVIEW

**Comment by alcides** [comment]
Blocked by https://github.com/actions/setup-python/pull/958

**Comment by alcides** [comment]
Check this alternative: https://github.com/actions/setup-python/issues/771

**Comment by ngoldbaum** [comment]
FWIW, we have a fork of setup-python with free-threading support that you can use: https://github.com/Quansight-Labs/setup-python

Keep in mind there are some caveats on Windows we're looking at fixing: Quansight-Labs/setup-python#5

**Comment by GUIpsp** [comment]
I think you should bite the bullet and switch to setup-uv

**Pull request closed without merging**
