### PR TITLE
New external API

### PR DESCRIPTION
**Pull request by alcides**
- GP is now more programatic
- the old GP class is now SimpleGP
- Documentation is more comprehensive.

### CODE REVIEW

**Comment by Leoningel** [comment]
PGE is still not working for linear string representations. See issue #80.

**Comment by Leoningel** [comment]
@alcides 
- Tests haven't completed
- Extra columns in CSVCallback not working
- Evolution is better, but still not always increasing (e.g. classification.py)
- There are many prints that are not necessary

**Comment by alcides** [comment]
I will need more details:

* What tests are not completed? I have 35 tests passed.
* Extra_columns are now being used with test_data.
* Prints have been removed, but now it is harder to test why elitism is not working.

**Comment by Leoningel** [comment]
I will need more details:
    What tests are not completed? I have 35 tests passed.
                    - The checks here in Github don't pass!
    Extra_columns are now being used with test_data.
                    - Great. So they are working now?
    Prints have been removed, but now it is harder to test why elitism is not working.
                    - Well, let's get elitism working first! Do you want me to look at it?

**Comment by alcides** [comment]
Can you provide me an example where elitism is not working?

**Comment by Leoningel** [comment]
> @alcides
> 
>     * Tests haven't completed
> 
>     * Extra columns in CSVCallback not working
> 
>     * Evolution is better, but still not always increasing (e.g. classification.py)
> 
>     * There are many prints that are not necessary

Some time ago classification.py wasn't working!

**Comment by alcides** [comment]
Found and fixed the elitism bug!

**Comment by alcides** [comment]
All tests pass.
All examples run, except one (pymax).
Examples were refactored to provide a Benchmark class, with a problem and grammar available.

**Comment by alcides** [comment]
it has now reached feature-parity with main. So it's ready to replace main.

**Comment by alcides** [comment]
Pymax fixed!

**Comment by Leoningel** [comment]
There are still some issues: 
- Elitsm still doesn't work for santafe
- Regression and classification get horrible results (looking at the individuals, regression result is 4/7, and classification is x_0 * 0.01, and changing the population size/number of generation/seed doesn't change these results)

**Comment by alcides** [comment]
This should have been addressed. I fixed it using a deep copy of the population. This might make it slower, but clearly there are mutation/crossovers that are mutable.

**Pull request closed without merging**
