### PR TITLE
Adds Lexicase selection

### LINKED ISSUE #55: Lexicase selection
http://williamlacava.com/research/lexicase/

### PR DESCRIPTION
**Pull request by alcides**
Closes #55.

### CODE REVIEW

**Comment by alcides** [comment]
Closes #64 when done.

**Review by Leoningel — CHANGES_REQUESTED** [review]
The progsys examples have not been edited to fit the new representation method implemented. Could you please do that?

**Comment by Leoningel** [comment]
Another question: What are we going to do with the elitism method? Will this be implemented as part of this PR or in another issue? I believe it might be easiest to do it now!

**Review by Leoningel — CHANGES_REQUESTED** [review]
Another thing: would you be able to add documentation on the selection methods? Have a look how I did it in the main branch for the Individual Representation and Grammars. It would be great if you could add a readme in the generation_steps folder that covers that whole folder. Also, in the core folder, you might want to add something on the new Problem classes. If you need help with this, let me know!

**Comment by eduardomadeira98** [comment]
I will do the merge later today, or tomorrow! 
I still have to finish the documentation that Leon asked, also I want to talk about the lexicase elitism in today's meeting, because I am having doubts about that.
And I think that I'll  probably have to change the function signature to receive the Problem as a parameter in order to distinguish if it's finding elites for a single or multi objetive problem.

**Comment by eduardomadeira98** [comment]
I just commited some code changes fixing a bug I was getting by doing "n_elites=0", and the commit does not appear in this pull request, but I commited the changes to the lexicase_selection branch. Is it a synchronization issue?

**Comment by alcides** [comment]
```bash
git checkout master
git pull origin master
git checkout lexicase_selection
git merge master
git push origin lexical_selection
```

**Pull request merged**
